[project]
name = "dsp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hdbscan>=0.8.40",
    "jupyterlab>=4.4.0",
    "matplotlib>=3.10.0",
    "pytorch-metric-learning>=2.8.1",
    "pytest>=8.3.5",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "speechbrain>=1.0.3",
    "torch>=2.13.0",
    "torchcodec>=0.8.1",
    "torchaudio>=2.11.0",
]

[project.scripts]
dsp501 = "run:main"

[tool.pytest.ini_options]
pythonpath = ["."]
